global:
  scrape_interval:     5s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['pet-monitoring:8080']

  - job_name: 'prometheus'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['pet-monitoring:9090']